name: poc_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_naver_login: ^1.8.0
  kakao_flutter_sdk_user: ^1.9.1+2
  sign_in_with_apple: ^6.1.1
  flutter_inappwebview: ^6.0.0
  http: ^1.2.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
